/*
 * This file is generated by jOOQ.
 */
package org.estafet.jooqModels.tables;


import java.util.Arrays;
import java.util.List;

import org.estafet.jooqModels.Keys;
import org.estafet.jooqModels.Public;
import org.estafet.jooqModels.tables.records.SuppliersAddressesRecord;
import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuppliersAddresses extends TableImpl<SuppliersAddressesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.suppliers_addresses</code>
     */
    public static final SuppliersAddresses SUPPLIERS_ADDRESSES = new SuppliersAddresses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SuppliersAddressesRecord> getRecordType() {
        return SuppliersAddressesRecord.class;
    }

    /**
     * The column <code>public.suppliers_addresses.id</code>.
     */
    public final TableField<SuppliersAddressesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.suppliers_addresses.address</code>.
     */
    public final TableField<SuppliersAddressesRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.suppliers_addresses.city</code>.
     */
    public final TableField<SuppliersAddressesRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.suppliers_addresses.province</code>.
     */
    public final TableField<SuppliersAddressesRecord, String> PROVINCE = createField(DSL.name("province"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.suppliers_addresses.state</code>.
     */
    public final TableField<SuppliersAddressesRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.suppliers_addresses.postal_code</code>.
     */
    public final TableField<SuppliersAddressesRecord, Integer> POSTAL_CODE = createField(DSL.name("postal_code"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.suppliers_addresses.country</code>.
     */
    public final TableField<SuppliersAddressesRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private SuppliersAddresses(Name alias, Table<SuppliersAddressesRecord> aliased) {
        this(alias, aliased, null);
    }

    private SuppliersAddresses(Name alias, Table<SuppliersAddressesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.suppliers_addresses</code> table reference
     */
    public SuppliersAddresses(String alias) {
        this(DSL.name(alias), SUPPLIERS_ADDRESSES);
    }

    /**
     * Create an aliased <code>public.suppliers_addresses</code> table reference
     */
    public SuppliersAddresses(Name alias) {
        this(alias, SUPPLIERS_ADDRESSES);
    }

    /**
     * Create a <code>public.suppliers_addresses</code> table reference
     */
    public SuppliersAddresses() {
        this(DSL.name("suppliers_addresses"), null);
    }

    public <O extends Record> SuppliersAddresses(Table<O> child, ForeignKey<O, SuppliersAddressesRecord> key) {
        super(child, key, SUPPLIERS_ADDRESSES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SuppliersAddressesRecord, Integer> getIdentity() {
        return (Identity<SuppliersAddressesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SuppliersAddressesRecord> getPrimaryKey() {
        return Keys.SUPPLIERS_ADDRESSES_PKEY;
    }

    @Override
    public List<Check<SuppliersAddressesRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("suppliers_addresses_postal_code_check"), "((postal_code > 0))", true)
        );
    }

    @Override
    public SuppliersAddresses as(String alias) {
        return new SuppliersAddresses(DSL.name(alias), this);
    }

    @Override
    public SuppliersAddresses as(Name alias) {
        return new SuppliersAddresses(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SuppliersAddresses rename(String name) {
        return new SuppliersAddresses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SuppliersAddresses rename(Name name) {
        return new SuppliersAddresses(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
