/*
 * This file is generated by jOOQ.
 */
package org.estafet.jooqModels.tables.records;


import java.time.OffsetDateTime;

import org.estafet.jooqModels.tables.Customers;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record12<Integer, String, String, String, Integer, Boolean, Boolean, OffsetDateTime, OffsetDateTime, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customers.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.customers.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.customers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.customers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customers.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.customers.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customers.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.customers.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.customers.age</code>.
     */
    public void setAge(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.customers.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.customers.gdpr_set</code>.
     */
    public void setGdprSet(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.customers.gdpr_set</code>.
     */
    public Boolean getGdprSet() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.customers.active</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.customers.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.customers.created_time</code>.
     */
    public void setCreatedTime(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.customers.created_time</code>.
     */
    public OffsetDateTime getCreatedTime() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.customers.updated_time</code>.
     */
    public void setUpdatedTime(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.customers.updated_time</code>.
     */
    public OffsetDateTime getUpdatedTime() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.customers.reason_for_deactivation</code>.
     */
    public void setReasonForDeactivation(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.customers.reason_for_deactivation</code>.
     */
    public String getReasonForDeactivation() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.customers.notes</code>.
     */
    public void setNotes(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.customers.notes</code>.
     */
    public String getNotes() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.customers.address_id</code>.
     */
    public void setAddressId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.customers.address_id</code>.
     */
    public Integer getAddressId() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, String, Integer, Boolean, Boolean, OffsetDateTime, OffsetDateTime, String, String, Integer> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, String, Integer, Boolean, Boolean, OffsetDateTime, OffsetDateTime, String, String, Integer> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customers.CUSTOMERS.CUSTOMER_ID;
    }

    @Override
    public Field<String> field2() {
        return Customers.CUSTOMERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return Customers.CUSTOMERS.PHONE;
    }

    @Override
    public Field<Integer> field5() {
        return Customers.CUSTOMERS.AGE;
    }

    @Override
    public Field<Boolean> field6() {
        return Customers.CUSTOMERS.GDPR_SET;
    }

    @Override
    public Field<Boolean> field7() {
        return Customers.CUSTOMERS.ACTIVE;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return Customers.CUSTOMERS.CREATED_TIME;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return Customers.CUSTOMERS.UPDATED_TIME;
    }

    @Override
    public Field<String> field10() {
        return Customers.CUSTOMERS.REASON_FOR_DEACTIVATION;
    }

    @Override
    public Field<String> field11() {
        return Customers.CUSTOMERS.NOTES;
    }

    @Override
    public Field<Integer> field12() {
        return Customers.CUSTOMERS.ADDRESS_ID;
    }

    @Override
    public Integer component1() {
        return getCustomerId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public Integer component5() {
        return getAge();
    }

    @Override
    public Boolean component6() {
        return getGdprSet();
    }

    @Override
    public Boolean component7() {
        return getActive();
    }

    @Override
    public OffsetDateTime component8() {
        return getCreatedTime();
    }

    @Override
    public OffsetDateTime component9() {
        return getUpdatedTime();
    }

    @Override
    public String component10() {
        return getReasonForDeactivation();
    }

    @Override
    public String component11() {
        return getNotes();
    }

    @Override
    public Integer component12() {
        return getAddressId();
    }

    @Override
    public Integer value1() {
        return getCustomerId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public Integer value5() {
        return getAge();
    }

    @Override
    public Boolean value6() {
        return getGdprSet();
    }

    @Override
    public Boolean value7() {
        return getActive();
    }

    @Override
    public OffsetDateTime value8() {
        return getCreatedTime();
    }

    @Override
    public OffsetDateTime value9() {
        return getUpdatedTime();
    }

    @Override
    public String value10() {
        return getReasonForDeactivation();
    }

    @Override
    public String value11() {
        return getNotes();
    }

    @Override
    public Integer value12() {
        return getAddressId();
    }

    @Override
    public CustomersRecord value1(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public CustomersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CustomersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomersRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public CustomersRecord value5(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public CustomersRecord value6(Boolean value) {
        setGdprSet(value);
        return this;
    }

    @Override
    public CustomersRecord value7(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public CustomersRecord value8(OffsetDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public CustomersRecord value9(OffsetDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public CustomersRecord value10(String value) {
        setReasonForDeactivation(value);
        return this;
    }

    @Override
    public CustomersRecord value11(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public CustomersRecord value12(Integer value) {
        setAddressId(value);
        return this;
    }

    @Override
    public CustomersRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Boolean value6, Boolean value7, OffsetDateTime value8, OffsetDateTime value9, String value10, String value11, Integer value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer customerId, String name, String email, String phone, Integer age, Boolean gdprSet, Boolean active, OffsetDateTime createdTime, OffsetDateTime updatedTime, String reasonForDeactivation, String notes, Integer addressId) {
        super(Customers.CUSTOMERS);

        setCustomerId(customerId);
        setName(name);
        setEmail(email);
        setPhone(phone);
        setAge(age);
        setGdprSet(gdprSet);
        setActive(active);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setReasonForDeactivation(reasonForDeactivation);
        setNotes(notes);
        setAddressId(addressId);
    }
}
