/*
 * This file is generated by jOOQ.
 */
package org.estafet.jooqModels.tables.records;


import org.estafet.jooqModels.tables.OrdersProductQuantities;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersProductQuantitiesRecord extends UpdatableRecordImpl<OrdersProductQuantitiesRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders_product_quantities.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders_product_quantities.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.orders_product_quantities.pid</code>.
     */
    public void setPid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders_product_quantities.pid</code>.
     */
    public Integer getPid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.orders_product_quantities.oid</code>.
     */
    public void setOid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders_product_quantities.oid</code>.
     */
    public Integer getOid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.orders_product_quantities.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders_product_quantities.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrdersProductQuantities.ORDERS_PRODUCT_QUANTITIES.ID;
    }

    @Override
    public Field<Integer> field2() {
        return OrdersProductQuantities.ORDERS_PRODUCT_QUANTITIES.PID;
    }

    @Override
    public Field<Integer> field3() {
        return OrdersProductQuantities.ORDERS_PRODUCT_QUANTITIES.OID;
    }

    @Override
    public Field<Integer> field4() {
        return OrdersProductQuantities.ORDERS_PRODUCT_QUANTITIES.QUANTITY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPid();
    }

    @Override
    public Integer component3() {
        return getOid();
    }

    @Override
    public Integer component4() {
        return getQuantity();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPid();
    }

    @Override
    public Integer value3() {
        return getOid();
    }

    @Override
    public Integer value4() {
        return getQuantity();
    }

    @Override
    public OrdersProductQuantitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrdersProductQuantitiesRecord value2(Integer value) {
        setPid(value);
        return this;
    }

    @Override
    public OrdersProductQuantitiesRecord value3(Integer value) {
        setOid(value);
        return this;
    }

    @Override
    public OrdersProductQuantitiesRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public OrdersProductQuantitiesRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersProductQuantitiesRecord
     */
    public OrdersProductQuantitiesRecord() {
        super(OrdersProductQuantities.ORDERS_PRODUCT_QUANTITIES);
    }

    /**
     * Create a detached, initialised OrdersProductQuantitiesRecord
     */
    public OrdersProductQuantitiesRecord(Integer id, Integer pid, Integer oid, Integer quantity) {
        super(OrdersProductQuantities.ORDERS_PRODUCT_QUANTITIES);

        setId(id);
        setPid(pid);
        setOid(oid);
        setQuantity(quantity);
    }
}
